name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log
